### ISSUE TITLE
using isRateLimitError fails on Error

### ISSUE THREAD

**Issue by amp127** [get-convex/ratelimiter#3]
If any other errors are called downstream of a function with rateLimiter.limit() i get this error on the ui when processing the error via isRateLimitError. 

 "TypeError: cannot use 'in' operator to search for "kind" in " if non-rate limit error gets triggered.

```
export function isRateLimitError(
  error: unknown,
): error is { data: RateLimitError } {
  return (
    error instanceof ConvexError &&
    "kind" in error.data &&
    error.data.kind === "RateLimited"
  );
} 
```
the fix would be 
```
export function isRateLimitError(
  error: unknown
): error is { data: RateLimitError } {
  console.log('isRateLimitError', { error })
  return error instanceof ConvexError &&
    error.data['kind'] &&
    error.data.kind === 'RateLimited'
    ? true
    : false
}
```
this is also a issue on convex-helpers

**Comment by ianmacartney** [comment]
Thanks for the report! Just published a fix to npm for helpers & the
component
